name: "Setup"
description: "Sets up the repository"
runs:
  using: "composite"
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.7.0
        node-version: 20

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: 20

    - name: Install dependencies
      shell: bash
      run: pnpm i --no-frozen-lockfile
