name: Checks

on:
  pull_request:
    types: [opened, synchronize]

env:
  NEXT_PUBLIC_BLUE_API_URL: ${{ vars.NEXT_PUBLIC_BLUE_API_URL }}
  NEXT_PUBLIC_REWARDS_API_URL: ${{ vars.NEXT_PUBLIC_REWARDS_API_URL }}
  NEXT_PUBLIC_REOWN_APP_ID: ${{ vars.NEXT_PUBLIC_REWARDS_REOWN_APP_ID }}
  NEXT_PUBLIC_BLUE_SERVICES_API: ${{ vars.NEXT_PUBLIC_BLUE_SERVICES_API }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run lint
        run: pnpm run lint

      - name: Run prettier
        run: pnpm run format

  Typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run typecheck
        run: pnpm run typecheck

  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: pnpm run test:unit
