# Has to be done manually instead of with Vercel because of URL workaround to
# use rewards.morpho.org
name: Build and Push Rewards App

on:
  push:
    branches: [main, dev]

permissions:
  id-token: write
  contents: read

env:
  ECR_REPOSITORY: prime-monorepo

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: ./
          file: ./apps/rewards-app/Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_BLUE_API_URL=${{ vars.NEXT_PUBLIC_BLUE_API_URL }}
            NEXT_PUBLIC_REWARDS_API_URL=${{ vars.NEXT_PUBLIC_REWARDS_API_URL }}
            NEXT_PUBLIC_REOWN_APP_ID=${{ vars.NEXT_PUBLIC_REWARDS_REOWN_APP_ID }}
            NEXT_PUBLIC_BLUE_SERVICES_API=${{ vars.NEXT_PUBLIC_BLUE_SERVICES_API }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

  update-image-tags:
    name: Update Infrastructure Image Tags
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Update Infrastructure Tags V2
        uses: morpho-org/update-infra-image-tag@v2
        with:
          app_id: ${{ secrets.INFRA_DEPLOYER_APP_ID }}
          app_private_key: ${{ secrets.INFRA_DEPLOYER_SECRET_KEY }}
          environments: dev,main
